repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-vcs-permalinks
      - id: trailing-whitespace
        types: [non-executable, file, text]
        exclude_types: [markdown]
      - id: mixed-line-ending
      - id: end-of-file-fixer
        types: [non-executable, file, text]
        exclude: input*
        exclude_types: [markdown]
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        entry: make format
        files: \.ex$
        pass_filenames: false
      - id: credo
        name: credo
        language: system
        entry: make credo
        files: \.ex$
        pass_filenames: false
      - id: dialyzer
        name: dialyzer
        language: system
        entry: make dialyzer
        files: \.ex$
        pass_filenames: false
      - id: test
        name: test
        language: system
        entry: make test
        files: \.ex$
        pass_filenames: false
